# Ubuntu FAI Build System - Conda Environment Configuration
# 使用 conda 管理 Python 依赖和环境

name: ubuntu-fai
channels:
  - conda-forge

dependencies:
  # Python 核心版本 - 使用3.11以获得更好的兼容性
  - python=3.11

  # 核心运行时依赖
  - pydantic>=2.5,<3.0
  - jinja2>=3.1,<4.0
  - pyyaml>=6.0,<7.0
  - requests>=2.31,<3.0
  - click>=8.1,<9.0
  - typing-extensions>=4.9,<5.0

  # 开发和验证工具
  - pytest>=7.4,<8.0
  - pytest-cov>=4.1,<5.0
  - pytest-mock>=3.12,<4.0

  # 代码质量工具
  - black>=23.0,<25.0
  - mypy>=1.8,<2.0
  - isort>=5.13,<6.0

  # 安全检查工具
  - bandit>=1.7,<2.0

  # 文档生成（可选）
  - sphinx>=7.2,<8.0

  # 构建和打包工具
  - wheel>=0.42,<1.0

  # 通过 pip 安装的依赖（conda 中不可用的包）
  - pip
  - pip:
    # 使用pip安装一些在conda中有兼容性问题的包
    - ruff>=0.1.0,<1.0
    - safety>=3.0,<4.0
    - sphinx-rtd-theme>=2.0,<3.0
    - pytest-asyncio>=0.23,<1.0
    - build>=1.0,<2.0

# 开发环境变量
variables:
  PYTHONPATH: $CONDA_PREFIX/src
  FAI_PROJECT_ROOT: $CONDA_PREFIX
  PYTHONUNBUFFERED: "1"

# 环境激活后运行的命令
# 注意：这些在 conda env create 时不会运行，需要在激活后手动运行或通过脚本