#!/bin/bash
# Dynamic FAI Class Configuration
# Generated by Ubuntu FAI Build System
# Hardware: HardwareVendor.DELL
# Encryption: True

# Set error handling
set -euo pipefail

# FAI class assignment based on configuration
# Classes are processed in order - later classes override earlier ones

# Base classes - always assigned
echo "UBUNTU"
echo "UBUNTU_DESKTOP" 
echo "AMD64"

# Hardware-specific classes
echo "HARDWARE_DELL"

# Disk and storage classes
echo "TARGET_SSD"


# Encryption classes
echo "UBUNTU_ENCRYPTED"
echo "LUKS_AES_XTS_PLAIN64"
echo "LUKS_KEYSIZE_256"

# Package and software classes
echo "CUSTOM_SOFTWARE"

echo "SNAP_PACKAGES"

# Network configuration classes
echo "NETWORK_DHCP"

# User configuration classes
echo "SSH_KEYS"


# First-boot classes
echo "FIRST_BOOT"
echo "FIRST_BOOT_AUTO"
echo "FIRST_BOOT_AUTO"
echo "FIRST_BOOT_MANUAL"

# Development and tools classes
echo "DEVELOPMENT_TOOLS"

# Docker class if docker packages are included
echo "DOCKER"

# Multimedia class for media packages
echo "MULTIMEDIA"

# Office productivity class
echo "OFFICE_PRODUCTIVITY"

# Security tools class

# Final class - always last to ensure proper ordering
echo "FAIEND"

# Export variables for use in other FAI scripts
export FAI_HARDWARE_VENDOR="HardwareVendor.DELL"
export FAI_ENCRYPTION_ENABLED="true"
export FAI_USER_NAME="ubuntu"
export FAI_HOSTNAME="ubuntu-fai-desktop"
export FAI_BUILD_TIMESTAMP="2025-07-18T14:11:48.147044"

# Log class assignment for debugging
{
    echo "=== FAI Class Assignment ==="
    echo "Hardware Vendor: HardwareVendor.DELL"
    echo "Target SSD: True"
    echo "Encryption Enabled: True"
echo "Encryption Cipher: aes-xts-plain64"
    echo "Key Size: 256"
echo "Custom Packages: 13"
    echo "DEB URLs: 2"
    echo "First Boot Scripts: 3"
    echo "Build Date: 2025-07-18T14:11:48.147044"
    echo "==========================="
} >> $LOGDIR/fai-class-assignment.log 2>/dev/null || true